name: bnow-checkinout

services:
  migrate:
    build:
      context: .
      target: migrate
    env_file:
      - path: .env.production.local
    restart: "no"
    networks:
      - default
      - hr-database

  app:
    build:
      context: .
      target: runner
    env_file:
      - path: .env.production.local
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "127.0.0.1:3010:3000"
    restart: unless-stopped
    init: true
    networks:
      - default
      - hr-database

  data-migrate:
    profiles: ["data-migration"]
    build:
      context: .
      target: data-migrate
    env_file:
      - path: .env.migration.local
    restart: "no"
    networks:
      - default
      - hr-database

networks:
  hr-database:
    external: true
    name: bnow-hr-database
