SET NOCOUNT ON;

IF COL_LENGTH('dbo.CHECKINOUT_EMPLOYEE', 'LOGIN_ID') IS NULL
    ALTER TABLE dbo.CHECKINOUT_EMPLOYEE ADD LOGIN_ID NVARCHAR(255) NULL;
IF COL_LENGTH('dbo.CHECKINOUT_EMPLOYEE', 'HIRED_ON') IS NULL
    ALTER TABLE dbo.CHECKINOUT_EMPLOYEE ADD HIRED_ON DATE NULL;
IF COL_LENGTH('dbo.CHECKINOUT_EMPLOYEE', 'LEAVE_GROUP') IS NULL
    ALTER TABLE dbo.CHECKINOUT_EMPLOYEE ADD LEAVE_GROUP NVARCHAR(100) NULL;
IF COL_LENGTH('dbo.CHECKINOUT_EMPLOYEE', 'RESIGNED_ON') IS NULL
    ALTER TABLE dbo.CHECKINOUT_EMPLOYEE ADD RESIGNED_ON DATE NULL;

SELECT
    COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
  AND TABLE_NAME = 'CHECKINOUT_EMPLOYEE'
ORDER BY ORDINAL_POSITION;
