SET NOCOUNT ON;

SELECT
    TABLE_NAME,
    COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN (
    'CHECKINOUT_EMPLOYEE',
    'CHECKINOUT_ATTENDANCE_RECORD',
    'CHECKINOUT_ANNUAL_LEAVE_BALANCE'
)
ORDER BY TABLE_NAME, ORDINAL_POSITION;
